### PR TITLE
better root checking & process redirect fixing

### PR DESCRIPTION
**Pull request by TitanSnow**
I write `os.uid()` to get uid instead of `id -u`

I modified the open mode of `process.open()` & `process.openv()`. Seems that the redirection has been fixed by this

### CODE REVIEW

**Comment by TitanSnow** [comment]
Seems to have trouble on appveyor

**Comment by waruqi** [comment]
Great! Some of the tests in the `tests/modules/os/` didn't go through on windows, but `assert` didn't give me more detail location information, so I tried to improve the `assert`.

**Comment by waruqi** [comment]
`copy empty dir` seems to have some problems on windows. I will look at it.

**Comment by TitanSnow** [comment]
It's better to let `assert` support context view

**Pull request merged**
