### PR TITLE
xmake getter improved

### PR DESCRIPTION
**Pull request by TitanSnow**
:white_check_mark: supported

:x: not supported

:heavy_minus_sign: partial supported

* `get.sh`
  * package manager :package: (platform) tested by docker :whale: 
    * :white_check_mark: apt-get
        * :white_check_mark: ubuntu
        * :white_check_mark: debian
    * :white_check_mark: yum
        * :white_check_mark: centos
        * :white_check_mark: fedora
    * :white_check_mark: zypper
        * :white_check_mark: opensuse
    * :white_check_mark: pacman
        * :white_check_mark: archlinux
    * :white_check_mark: homebrew
        * :white_check_mark: homebrew
        * :white_check_mark: linuxbrew
    * :x: macports
    * :x: portage
  * features :flags: 
    * :white_check_mark: get newest :octocat: with branch specified
    * :white_check_mark: build tool check & install :chains: 
    * :white_check_mark: auto build :building_construction: 
    * :white_check_mark: path detection :house: 
    * :white_check_mark: error log with color :rainbow: 
    * :heavy_minus_sign: no root requirement (partial) :family_man_woman_girl: 
    * :white_check_mark: local git repo install :hammer: 
    * :white_check_mark: cleanup :feet:
* `get.ps1`
  * platform :factory: 
    * :white_check_mark: Windows 10
    * :white_check_mark: Windows Server 2016
    * :heavy_minus_sign: Windows 8 (update powershell)
    * :heavy_minus_sign: Windows 7 (update powershell)
    * :x: Windows XP
  * features :flags: 
    * :white_check_mark: get newest :octocat: with branch specified
    * :x: build tool check & install :chains: 
    * :white_check_mark: auto build :building_construction: 
    * :white_check_mark: path detection :house: 
    * :white_check_mark: error log with color :rainbow: 
    * :white_check_mark: no administrator requirement :family_man_woman_girl: 
    * :x: local git repo install :hammer: 
    * :white_check_mark: cleanup :feet:

### CODE REVIEW

**Comment by waruqi** [comment]
This is awesome. 👍

**Comment by TitanSnow** [comment]
Just so so :smile_cat:

**Comment by waruqi** [comment]
I modified logo for get script 67327cae080901ac773b482804d427d172bf29e3 and add this shell command to homepage: [http://xmake.io](http://xmake.io) 😸

**Comment by TitanSnow** [comment]
Nice!

**Comment by TitanSnow** [comment]
Some improvement

Origin
```console
$ bash <(curl -fsSL https://raw.githubusercontent.com/tboox/xmake/master/scripts/get.sh)
```

* There is a shorter URL for raw script I found these days -- [https://github.com/tboox/xmake/raw/master/scripts/get.sh](https://github.com/tboox/xmake/raw/master/scripts/get.sh)
* `curl` is not preinstalled on every linux. For example ubuntu. But `wget` must be preinstalled. So that use `wget` instead of `curl` might be better, like `wget https://github.com/tboox/xmake/raw/master/scripts/get.sh -O -`

Improved:
``` console
$ bash <(wget https://github.com/tboox/xmake/raw/master/scripts/get.sh -O -)
```

**Comment by waruqi** [comment]
@TitanSnow But wget does not seem to be preinstalled on the macOS.

**Comment by TitanSnow** [comment]
[oh-my-zsh](https://github.com/robbyrussell/oh-my-zsh#basic-installation) lists two ways both:

-------------

### Basic Installation

Oh My Zsh is installed by running one of the following commands in your terminal. You can install this via the command-line with either `curl` or `wget`.

#### via curl

```shell
sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
```

#### via wget

```shell
sh -c "$(wget https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh -O -)"
```

-------------

So we could also do so

**Comment by waruqi** [comment]
I have improved documents.

**Pull request merged**
