### PR TITLE
make all

### PR DESCRIPTION
**Pull request by TitanSnow**
`make`: make default targets

`make all`: make all targets

### CODE REVIEW

**Comment by TitanSnow** [comment]
By the way, is there something like coverage for xmake? @waruqi

**Comment by waruqi** [comment]
👍

**Comment by waruqi** [comment]
@TitanSnow `--coverage`?  [codecov](https://codecov.io/gh/tboox/tbox)?

**Comment by TitanSnow** [comment]
Yep

**Comment by waruqi** [comment]
not yet

**Comment by waruqi** [comment]
I have added codecov token to travis-ci for [xmake-codecov](https://codecov.io/gh/tboox/xmake). But I haven't modified travis.yml to upload coverage data to codecov.

**Comment by TitanSnow** [comment]
I'm afraid testsuite for xmake would be a large work. So for writing tests, how do you think?

**Comment by waruqi** [comment]
I writed  some tests  in xmake/tests directory and we can run tests/test script on ci

**Comment by TitanSnow** [comment]
I would like to do some modify on .travis.yml

**Comment by waruqi** [comment]
we can try to use [luacov](https://keplerproject.github.io/luacov/)?

**Comment by TitanSnow** [comment]
Great :+1:

**Pull request merged**
