### PR TITLE
semver

### PR DESCRIPTION
**Pull request by uael**
- [x] semver:resolve
- [x] add more tests

### CODE REVIEW

**Comment by uael** [comment]
#69

**Comment by waruqi** [comment]
@uael I found `semver.select()` will return version 1.7.0 when I test `add_requires("https://github.com/glennrp/libpng.git@libpng >=1.6.28")`. But the version tags of libpng is `v1.7.0beta87 ...`.

How to get the original version string in the returned version, for exmaple:

```
local version, source = semver.select(">= 1.6.28", {}, {"v1.7.0beta87"}, {})

version = 
{
    version = 1.7.0
    origin = v1.7.0beta87  <- return raw version string
    major = 1
    minor = 7
}
```

**Comment by waruqi** [comment]
@uael If I choose master but no branch, it would be better to choose the newest version, rather than simply returning the empty

```lua
local version, source = semver.select("master", {"1.8.0, 1.9.0"}, {"1.7.0", "1.6.0"}, {})
```

return version: 1.9.0

**Comment by uael** [comment]
@waruqi hum 1.7.0beta87 isn't a valid version it should be 1.7.0-beta+87
Ok for master you're right 👍

**Comment by waruqi** [comment]
@uael > hum 1.7.0beta87 isn't a valid version it should be 1.7.0-beta+87

But there's a lot of irregular version numbers in git tags. For an irregular version number, if it is not handled, it should return empty, and if it can be handled, the original version string should be returned. Otherwise `git checkout` or download url will fail because I don't know if the returned version is valid.

for example, the returned version is `v1.7.0`, but I `git checkout v1.7.0` fails.

If the empty version `{}` is returned, I can at least ignore it, or return to the original version string `"v1.7.0beta87"` and I can checkout it normally.

```
> semver.select(">=1.6.28", {}, {"v1.7.0beta87"}, {})

{
    patch = 0
,   minor = 7
,   version = v1.7.0
,   major = 1
,   build = 
    {
    }

,   prerelease = 
    {
    }

}
 tags
```

**Comment by uael** [comment]
@waruqi I've tested and fixed most of the libsv, i will continue the xmake semver with latest changes once I release libsv as soon as possible.

**Comment by uael** [comment]
I dunno how to hanlde bad tags but I think you're right, the goal is to get files with a version as close as possible to the user input, which include bad versions

**Comment by waruqi** [comment]
@uael  Yes, and the returned version(`v1.7.0`)  maybe correct in this example, It's very similar to `v1.7.0beta87`.  Can you return this user input string `v1.7.0beta87` at same time when return `v1.7.0`

**Comment by uael** [comment]
np :smiley:

**Comment by uael** [comment]
About the resolver you should just concatenate range when you got a dependency twice like, a want d to be >1.5 and b want d to be <2 then you select:
```lua
semver.select(">1.5 <2", {...}, {...}, {...})
```

**Comment by uael** [comment]
@waruqi 
```lua
> semver = import("core.base.semver")
> semver.select(">=1.6.28", {}, {"v1.7.0beta87"}, {})

{
    patch = 0
,   raw = v1.7.0beta87
,   version = v1.7.0beta87
,   major = 1
,   build = 
    {
    }

,   minor = 7
,   prerelease = 
    {
        beta87
    }

}
 tags
```

**Comment by waruqi** [comment]
@uael 
> About the resolver you should just concatenate range when you got a dependency twice like, a want d to be >1.5 and b want d to be <2 then you select:

Ok, I will improve it. Thanks!

**Comment by waruqi** [comment]
@uael Can I merge this PR now?

**Comment by uael** [comment]
@waruqi Yep 😃

**Comment by waruqi** [comment]
Ok 👌

**Comment by waruqi** [comment]
@uael If you only use the bool type, this header file `<cstdbool>` does not seem to be necessary?When I use vs2008 to compile it as c++(`/TP`), this file not found!

```c
# ifdef __cplusplus
#  include <cstdbool>
# else
```

**Comment by uael** [comment]
@waruqi If it work on 2010 I ca check for it
```
MSVC++ 14.1 _MSC_VER == 1910 (Visual Studio 2017)
MSVC++ 14.0 _MSC_VER == 1900 (Visual Studio 2015)
MSVC++ 12.0 _MSC_VER == 1800 (Visual Studio 2013)
MSVC++ 11.0 _MSC_VER == 1700 (Visual Studio 2012)
MSVC++ 10.0 _MSC_VER == 1600 (Visual Studio 2010)
MSVC++ 9.0  _MSC_VER == 1500 (Visual Studio 2008)
MSVC++ 8.0  _MSC_VER == 1400 (Visual Studio 2005)
MSVC++ 7.1  _MSC_VER == 1310 (Visual Studio 2003)
MSVC++ 7.0  _MSC_VER == 1300
MSVC++ 6.0  _MSC_VER == 1200
MSVC++ 5.0  _MSC_VER == 1100
```

**Comment by waruqi** [comment]
@uael Is that okay? 

```c
# ifdef __cplusplus
#    if defined(_MSC_VER) && _MSC_VER >= 1600
#        include <cstdbool>
#    endif
# else
```

**Comment by uael** [comment]
@waruqi Yep I think, but you're maybe right
```c
#ifndef __cplusplus
# if defined(_MSC_VER) && _MSC_VER < 1900
#   define bool	unsigned char
#   define true	1
#   define false	0
#   define __bool_true_false_are_defined	1
# else
#   include <stdbool.h>
# endif
#endif
```
should work

**Comment by waruqi** [comment]
😄

**Comment by uael** [comment]
#114

**Pull request merged**
