### PR TITLE
Correct some grammar and spelling

### PR DESCRIPTION
**Pull request by shlomif**
Hi!

This pull-req corrects some grammar and spelling.

### CODE REVIEW

**Comment by waruqi** [comment]
Please commit pr to dev, thanks. You can see https://github.com/tboox/xmake/blob/master/CONTRIBUTING.md#pull-requests

**Comment by shlomif** [comment]
@waruqi : done, thanks! It was originally branched from dev as well. See https://stackoverflow.com/questions/10081053/how-to-change-the-base-branch-of-a-pull-request .

**Comment by waruqi** [comment]
Ok, thanks!

**Comment by shlomif** [comment]
Thanks!

**Pull request merged**
