### PR TITLE
testcase

### PR DESCRIPTION
**Pull request by TitanSnow**
**Stub**

Goal: add more testcases, inc coverage to 78%

Done: more powerful test script

### CODE REVIEW

**Comment by TitanSnow** [comment]
#100 :tada:

**Comment by uael** [comment]
That's sound great but lua should be used instead of python3

**Comment by uael** [comment]
xmake can test himself which increment the code coverage

**Comment by TitanSnow** [comment]
:smile_cat:

**Comment by waruqi** [comment]
@TitanSnow @uael 

> That's sound great but lua should be used instead of python3
> xmake can test himself which increment the code coverage

Right, I think we can use `xmake lua tests/tests.lua` to load all tests. 

```diff
+ "iphoneos":{
+        "platform":"darwin",
+        "steps":[
+            ["xmake","m","-P",null,"package","-p","iphoneos"]
+        ]
+    }
```

And using JSON to configure the test commands doesn't seem very flexible. I think it's better to use lua scripts directly and not depend on Python3. for example:

```
tests
   - test.lua
   - projects 
      - console_c
        - test.lua
      - static_library_c
        - test.lua
   - modules
      - semver
        - test.lua
      - other_modules
        - test.lua
```

for `tests/test.lua`:

```lua
import("core.project.task")
function main()
    -- run all tests
    for _, testfile in ipairs(os.files(path.join(os.scriptdir(), "**/test.lua"))) do
          os.cd(path.directory(testfile))
          task.run("lua", {script=testfile})
    end
end
```

for `tests/projects/static_library_c/test.lua`:

```lua
function main()
      os.exec("...")
end
```

**Comment by TitanSnow** [comment]
Please have a look at [build 1475](https://travis-ci.org/tboox/xmake/jobs/233987662). I use macro to run tests but it seems to have some problems. The behavior of `-P` on task `macro` looks straight. Is that a bug? @waruqi

**Comment by waruqi** [comment]
@TitanSnow The `xmake macro` can only be used within the single project for the time being, not supported across multiple projects. I will improve it in the future.

**Comment by uael** [comment]
@waruqi 
> for tests/.test.lua:

dot something are commonly hidden files, maybe just `tests/test.lua`

**Comment by waruqi** [comment]
@uael ok

**Comment by waruqi** [comment]
@TitanSnow @uael  I have improved test script, we can run all tests: `make test` or run the given test, for example:

```bash
$ make test
$ make test name=ping
$ make test name=semver
$ make test name=console_c
$ make test name=static_library_c
```

**Comment by TitanSnow** [comment]
Great! :+1:

**Pull request closed without merging**
