### PR TITLE
semver

### PR DESCRIPTION
**Pull request by uael**
I'm creating the pr to discuss about it :+1:

### CODE REVIEW

**Comment by uael** [comment]
I'm finally using pattern matching, which is safe, even if i prefer good old regex :+1: , to be as close as possible from the npm version.
If this version isn't efficient I'll probably wrap it in c.

**Comment by TitanSnow** [comment]
I think efficiency would never be a problem

I don't know lua but in python I think following could work:

```python
rst=re.search(r'(\d+)\.(\d+)\.(\d+)(?:-(.+))?',"2.1.4-alpha1")
if not rst:raise InvaidSemver()
print(rst.groups())
# will get: ('2', '1', '4', 'alpha1')
```

**Comment by waruqi** [comment]
@uael Ok, I will look at it. Thanks!

**Comment by waruqi** [comment]
@TitanSnow @uael  Yes, efficiency is not a problem and the version string is very short.

**Comment by uael** [comment]
Ok! :+1:

**Comment by uael** [comment]
How can i run the tests (with modules loading etc) ?

**Comment by waruqi** [comment]
@uael You can write module tests in the `xmake/tests/modules` directory or other tmpdir. for example: [tests/semver](https://github.com/tboox/xmake/blob/repo/tests/modules/semver.lua)

Then use `xmake [l|lua]` action to load lua script and run tests:

```bash
$ xmake l ./tests/modules/semver.lua
```

**Comment by uael** [comment]
Got a lot busy, but I'm back ! I'm going to continue the job tomorrow
Also, good job on repo :+1:

**Comment by waruqi** [comment]
😃

**Comment by uael** [comment]
Just realized what the sandbox did, and that you add me a note 13 days ago "this action only load and run modules in sandbox" :expressionless:

**Comment by uael** [comment]
I'm currently porting all my stuff to xmake, best build system ever :+1:

**Comment by TitanSnow** [comment]
A doc on deeply coding inside xmake? @waruqi 

My understand on stack of xmake: :smiley:

<table>
<tr><td colspan="2">sandbox: actions, plugins (load modules: <code>import</code>)</td></tr>
<tr><td colspan="2">== sandbox API (in <a href="https://github.com/tboox/xmake/tree/master/xmake/core/sandbox/modules">xmake/core/sandbox/modules</a>) ==</td></tr>
<tr><td colspan="2">core: tools (like <code>compiler.lua</code> etc) (load module: <code>require</code>)</td></tr>
<tr><td>== lua API ==</td><td>== ext API (in <a href="https://github.com/tboox/xmake/tree/master/core/src/xmake">core/src/xmake</a>) ==</td></tr>
<tr><td>luajit</td><td><code>os.</code>, <code>path.</code>, etc</td></tr>
</table>

Right?

**Comment by waruqi** [comment]
@TitanSnow  I've finished writing most of Chinese documents about sandbox and builtin modules. You can see [builtin-modules](http://xmake.io/#/manual?id=builtin-modules), [extension-modules](http://xmake.io/#/manual?id=extension-modules) and [plugins-dev](http://xmake.io/#/plugins)

But my English is poor and I don't have too much free time, so I haven't translated them yet. I'm terribly sorry about that. 

In the future I will continue to improve the English document.

**Comment by waruqi** [comment]
@TitanSnow 

|     run in      |     desc    |
| ----------- | --------- | 
| core            |  core basic modules, load sandbox, parse xmake.lua ... |
| sandbox     | uses exception (raise) to simplify code, separate scope, import modules | 
|                   | In most cases, you do not need to determine the return value |

- xmake
  - core (require core modules)
    - base
      - interpreter (parse xmake.lua)
      - other basic modules (require)
        - path
        - string
        - os
    - sandbox
       - loader (load actions, plugins, platforms, ...)
       - builtin modules (called in sandbox, need not import)
         - path
         - os
         - string 
         - ..
       - imports
         - extension modules
 
- run in sandbox (import sandbox modules)
  - actions		
  - languages
  - plugins
  - tools		
  - platforms	
  - templates

**Comment by waruqi** [comment]
Great! 👍

**Comment by TitanSnow** [comment]
Congratulations :tada:

**Comment by uael** [comment]
Ark just a commit to transfer changes done at my office and work at home this weekend 😄

**Pull request merged**
