### PR TITLE
semver

### PR DESCRIPTION
**Pull request by uael**
**pending**
See #92

### CODE REVIEW

**Comment by uael** [comment]
I dunno how i duplicate my commits

**Comment by waruqi** [comment]
@uael You can add includes `../sv/include` to `xmake/makefile.xmake_INC_DIRS`

```
xmake_INC_DIRS += \
                               ../luajit/src \
                               ../sv/include
```

```
semver/prefix.h:33:20: fatal error: semver.h: No such file or directory
Build Fail
```

**Comment by waruqi** [comment]
@uael duplicate commits? `cherry-pick`?

**Comment by uael** [comment]
@waruqi where to link `-lsv` ?

**Comment by uael** [comment]
> duplicate commits? cherry-pick?

Didn't used it, just rebased like you sowed me, weird

**Comment by waruqi** [comment]
@uael 
> where to link -lsv ?

`demo/makefile`:  `demo_LIBS += xmake$(DTYPE) luajit$(DTYPE) sv$(DTYPE)`

**Comment by waruqi** [comment]
> Didn't used it, just rebased like you sowed me, weird

But the new PR seems no problem

**Comment by uael** [comment]
Ok! I going to test the make build system before commit in future..

**Comment by waruqi** [comment]
👍

**Comment by waruqi** [comment]
It's great! 😄  ❤️

**Pull request merged**
